package com.smedia.sqzserver.dataservice.model.base;

public class ApplicationSettingsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ApplicationSettings.ApplicationSettingId
     *
     * @mbggenerated Mon Feb 06 21:11:44 MST 2012
     */
    private String applicationSettingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ApplicationSettings.Name
     *
     * @mbggenerated Mon Feb 06 21:11:44 MST 2012
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ApplicationSettings.ApplicationSettingId
     *
     * @return the value of ApplicationSettings.ApplicationSettingId
     *
     * @mbggenerated Mon Feb 06 21:11:44 MST 2012
     */
    public String getApplicationSettingId() {
        return applicationSettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ApplicationSettings.ApplicationSettingId
     *
     * @param applicationSettingId the value for ApplicationSettings.ApplicationSettingId
     *
     * @mbggenerated Mon Feb 06 21:11:44 MST 2012
     */
    public void setApplicationSettingId(String applicationSettingId) {
        this.applicationSettingId = applicationSettingId == null ? null : applicationSettingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ApplicationSettings.Name
     *
     * @return the value of ApplicationSettings.Name
     *
     * @mbggenerated Mon Feb 06 21:11:44 MST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ApplicationSettings.Name
     *
     * @param name the value for ApplicationSettings.Name
     *
     * @mbggenerated Mon Feb 06 21:11:44 MST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}