package com.smedia.sqzserver.dataservice.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DestinationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public DestinationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDestinationIdIsNull() {
            addCriterion("DestinationId is null");
            return (Criteria) this;
        }

        public Criteria andDestinationIdIsNotNull() {
            addCriterion("DestinationId is not null");
            return (Criteria) this;
        }

        public Criteria andDestinationIdEqualTo(String value) {
            addCriterion("DestinationId =", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdNotEqualTo(String value) {
            addCriterion("DestinationId <>", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdGreaterThan(String value) {
            addCriterion("DestinationId >", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdGreaterThanOrEqualTo(String value) {
            addCriterion("DestinationId >=", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdLessThan(String value) {
            addCriterion("DestinationId <", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdLessThanOrEqualTo(String value) {
            addCriterion("DestinationId <=", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdLike(String value) {
            addCriterion("DestinationId like", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdNotLike(String value) {
            addCriterion("DestinationId not like", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdIn(List<String> values) {
            addCriterion("DestinationId in", values, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdNotIn(List<String> values) {
            addCriterion("DestinationId not in", values, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdBetween(String value1, String value2) {
            addCriterion("DestinationId between", value1, value2, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdNotBetween(String value1, String value2) {
            addCriterion("DestinationId not between", value1, value2, "destinationId");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNull() {
            addCriterion("JobId is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("JobId is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(String value) {
            addCriterion("JobId =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(String value) {
            addCriterion("JobId <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(String value) {
            addCriterion("JobId >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(String value) {
            addCriterion("JobId >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(String value) {
            addCriterion("JobId <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(String value) {
            addCriterion("JobId <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLike(String value) {
            addCriterion("JobId like", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotLike(String value) {
            addCriterion("JobId not like", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<String> values) {
            addCriterion("JobId in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<String> values) {
            addCriterion("JobId not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(String value1, String value2) {
            addCriterion("JobId between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(String value1, String value2) {
            addCriterion("JobId not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdIsNull() {
            addCriterion("LocationTypeId is null");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdIsNotNull() {
            addCriterion("LocationTypeId is not null");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdEqualTo(Integer value) {
            addCriterion("LocationTypeId =", value, "locationTypeId");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdNotEqualTo(Integer value) {
            addCriterion("LocationTypeId <>", value, "locationTypeId");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdGreaterThan(Integer value) {
            addCriterion("LocationTypeId >", value, "locationTypeId");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("LocationTypeId >=", value, "locationTypeId");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdLessThan(Integer value) {
            addCriterion("LocationTypeId <", value, "locationTypeId");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("LocationTypeId <=", value, "locationTypeId");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdIn(List<Integer> values) {
            addCriterion("LocationTypeId in", values, "locationTypeId");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdNotIn(List<Integer> values) {
            addCriterion("LocationTypeId not in", values, "locationTypeId");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("LocationTypeId between", value1, value2, "locationTypeId");
            return (Criteria) this;
        }

        public Criteria andLocationTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("LocationTypeId not between", value1, value2, "locationTypeId");
            return (Criteria) this;
        }

        public Criteria andURIIsNull() {
            addCriterion("URI is null");
            return (Criteria) this;
        }

        public Criteria andURIIsNotNull() {
            addCriterion("URI is not null");
            return (Criteria) this;
        }

        public Criteria andURIEqualTo(String value) {
            addCriterion("URI =", value, "URI");
            return (Criteria) this;
        }

        public Criteria andURINotEqualTo(String value) {
            addCriterion("URI <>", value, "URI");
            return (Criteria) this;
        }

        public Criteria andURIGreaterThan(String value) {
            addCriterion("URI >", value, "URI");
            return (Criteria) this;
        }

        public Criteria andURIGreaterThanOrEqualTo(String value) {
            addCriterion("URI >=", value, "URI");
            return (Criteria) this;
        }

        public Criteria andURILessThan(String value) {
            addCriterion("URI <", value, "URI");
            return (Criteria) this;
        }

        public Criteria andURILessThanOrEqualTo(String value) {
            addCriterion("URI <=", value, "URI");
            return (Criteria) this;
        }

        public Criteria andURILike(String value) {
            addCriterion("URI like", value, "URI");
            return (Criteria) this;
        }

        public Criteria andURINotLike(String value) {
            addCriterion("URI not like", value, "URI");
            return (Criteria) this;
        }

        public Criteria andURIIn(List<String> values) {
            addCriterion("URI in", values, "URI");
            return (Criteria) this;
        }

        public Criteria andURINotIn(List<String> values) {
            addCriterion("URI not in", values, "URI");
            return (Criteria) this;
        }

        public Criteria andURIBetween(String value1, String value2) {
            addCriterion("URI between", value1, value2, "URI");
            return (Criteria) this;
        }

        public Criteria andURINotBetween(String value1, String value2) {
            addCriterion("URI not between", value1, value2, "URI");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNull() {
            addCriterion("FileName is null");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNotNull() {
            addCriterion("FileName is not null");
            return (Criteria) this;
        }

        public Criteria andFileNameEqualTo(String value) {
            addCriterion("FileName =", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotEqualTo(String value) {
            addCriterion("FileName <>", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThan(String value) {
            addCriterion("FileName >", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("FileName >=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThan(String value) {
            addCriterion("FileName <", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThanOrEqualTo(String value) {
            addCriterion("FileName <=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLike(String value) {
            addCriterion("FileName like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotLike(String value) {
            addCriterion("FileName not like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameIn(List<String> values) {
            addCriterion("FileName in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotIn(List<String> values) {
            addCriterion("FileName not in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameBetween(String value1, String value2) {
            addCriterion("FileName between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotBetween(String value1, String value2) {
            addCriterion("FileName not between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andSSSBucketIsNull() {
            addCriterion("SSSBucket is null");
            return (Criteria) this;
        }

        public Criteria andSSSBucketIsNotNull() {
            addCriterion("SSSBucket is not null");
            return (Criteria) this;
        }

        public Criteria andSSSBucketEqualTo(String value) {
            addCriterion("SSSBucket =", value, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketNotEqualTo(String value) {
            addCriterion("SSSBucket <>", value, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketGreaterThan(String value) {
            addCriterion("SSSBucket >", value, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketGreaterThanOrEqualTo(String value) {
            addCriterion("SSSBucket >=", value, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketLessThan(String value) {
            addCriterion("SSSBucket <", value, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketLessThanOrEqualTo(String value) {
            addCriterion("SSSBucket <=", value, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketLike(String value) {
            addCriterion("SSSBucket like", value, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketNotLike(String value) {
            addCriterion("SSSBucket not like", value, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketIn(List<String> values) {
            addCriterion("SSSBucket in", values, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketNotIn(List<String> values) {
            addCriterion("SSSBucket not in", values, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketBetween(String value1, String value2) {
            addCriterion("SSSBucket between", value1, value2, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andSSSBucketNotBetween(String value1, String value2) {
            addCriterion("SSSBucket not between", value1, value2, "SSSBucket");
            return (Criteria) this;
        }

        public Criteria andCredentialIdIsNull() {
            addCriterion("CredentialId is null");
            return (Criteria) this;
        }

        public Criteria andCredentialIdIsNotNull() {
            addCriterion("CredentialId is not null");
            return (Criteria) this;
        }

        public Criteria andCredentialIdEqualTo(String value) {
            addCriterion("CredentialId =", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdNotEqualTo(String value) {
            addCriterion("CredentialId <>", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdGreaterThan(String value) {
            addCriterion("CredentialId >", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdGreaterThanOrEqualTo(String value) {
            addCriterion("CredentialId >=", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdLessThan(String value) {
            addCriterion("CredentialId <", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdLessThanOrEqualTo(String value) {
            addCriterion("CredentialId <=", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdLike(String value) {
            addCriterion("CredentialId like", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdNotLike(String value) {
            addCriterion("CredentialId not like", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdIn(List<String> values) {
            addCriterion("CredentialId in", values, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdNotIn(List<String> values) {
            addCriterion("CredentialId not in", values, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdBetween(String value1, String value2) {
            addCriterion("CredentialId between", value1, value2, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdNotBetween(String value1, String value2) {
            addCriterion("CredentialId not between", value1, value2, "credentialId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("UserName is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("UserName is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("UserName =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("UserName <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("UserName >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("UserName >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("UserName <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("UserName <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("UserName like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("UserName not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("UserName in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("UserName not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("UserName between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("UserName not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("Password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("Password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("Password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("Password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("Password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("Password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("Password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("Password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("Password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("Password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("Password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("Password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("Password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("Password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("Salt is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("Salt is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("Salt =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("Salt <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("Salt >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("Salt >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("Salt <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("Salt <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("Salt like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("Salt not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("Salt in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("Salt not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("Salt between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("Salt not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketIsNull() {
            addCriterion("SSSThumbBucket is null");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketIsNotNull() {
            addCriterion("SSSThumbBucket is not null");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketEqualTo(String value) {
            addCriterion("SSSThumbBucket =", value, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketNotEqualTo(String value) {
            addCriterion("SSSThumbBucket <>", value, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketGreaterThan(String value) {
            addCriterion("SSSThumbBucket >", value, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketGreaterThanOrEqualTo(String value) {
            addCriterion("SSSThumbBucket >=", value, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketLessThan(String value) {
            addCriterion("SSSThumbBucket <", value, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketLessThanOrEqualTo(String value) {
            addCriterion("SSSThumbBucket <=", value, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketLike(String value) {
            addCriterion("SSSThumbBucket like", value, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketNotLike(String value) {
            addCriterion("SSSThumbBucket not like", value, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketIn(List<String> values) {
            addCriterion("SSSThumbBucket in", values, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketNotIn(List<String> values) {
            addCriterion("SSSThumbBucket not in", values, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketBetween(String value1, String value2) {
            addCriterion("SSSThumbBucket between", value1, value2, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andSSSThumbBucketNotBetween(String value1, String value2) {
            addCriterion("SSSThumbBucket not between", value1, value2, "SSSThumbBucket");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternIsNull() {
            addCriterion("ThumbFileNamePattern is null");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternIsNotNull() {
            addCriterion("ThumbFileNamePattern is not null");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternEqualTo(String value) {
            addCriterion("ThumbFileNamePattern =", value, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternNotEqualTo(String value) {
            addCriterion("ThumbFileNamePattern <>", value, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternGreaterThan(String value) {
            addCriterion("ThumbFileNamePattern >", value, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternGreaterThanOrEqualTo(String value) {
            addCriterion("ThumbFileNamePattern >=", value, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternLessThan(String value) {
            addCriterion("ThumbFileNamePattern <", value, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternLessThanOrEqualTo(String value) {
            addCriterion("ThumbFileNamePattern <=", value, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternLike(String value) {
            addCriterion("ThumbFileNamePattern like", value, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternNotLike(String value) {
            addCriterion("ThumbFileNamePattern not like", value, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternIn(List<String> values) {
            addCriterion("ThumbFileNamePattern in", values, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternNotIn(List<String> values) {
            addCriterion("ThumbFileNamePattern not in", values, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternBetween(String value1, String value2) {
            addCriterion("ThumbFileNamePattern between", value1, value2, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbFileNamePatternNotBetween(String value1, String value2) {
            addCriterion("ThumbFileNamePattern not between", value1, value2, "thumbFileNamePattern");
            return (Criteria) this;
        }

        public Criteria andThumbURIIsNull() {
            addCriterion("ThumbURI is null");
            return (Criteria) this;
        }

        public Criteria andThumbURIIsNotNull() {
            addCriterion("ThumbURI is not null");
            return (Criteria) this;
        }

        public Criteria andThumbURIEqualTo(String value) {
            addCriterion("ThumbURI =", value, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURINotEqualTo(String value) {
            addCriterion("ThumbURI <>", value, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURIGreaterThan(String value) {
            addCriterion("ThumbURI >", value, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURIGreaterThanOrEqualTo(String value) {
            addCriterion("ThumbURI >=", value, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURILessThan(String value) {
            addCriterion("ThumbURI <", value, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURILessThanOrEqualTo(String value) {
            addCriterion("ThumbURI <=", value, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURILike(String value) {
            addCriterion("ThumbURI like", value, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURINotLike(String value) {
            addCriterion("ThumbURI not like", value, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURIIn(List<String> values) {
            addCriterion("ThumbURI in", values, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURINotIn(List<String> values) {
            addCriterion("ThumbURI not in", values, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURIBetween(String value1, String value2) {
            addCriterion("ThumbURI between", value1, value2, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andThumbURINotBetween(String value1, String value2) {
            addCriterion("ThumbURI not between", value1, value2, "thumbURI");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("Created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("Created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("Created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("Created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("Created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("Created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("Created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("Created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("Created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("Created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("Created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("Created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("Modified is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("Modified is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("Modified =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("Modified <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("Modified >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("Modified >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("Modified <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("Modified <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("Modified in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("Modified not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("Modified between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("Modified not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdIsNull() {
            addCriterion("FileNamingMethodId is null");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdIsNotNull() {
            addCriterion("FileNamingMethodId is not null");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdEqualTo(Integer value) {
            addCriterion("FileNamingMethodId =", value, "fileNamingMethodId");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdNotEqualTo(Integer value) {
            addCriterion("FileNamingMethodId <>", value, "fileNamingMethodId");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdGreaterThan(Integer value) {
            addCriterion("FileNamingMethodId >", value, "fileNamingMethodId");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FileNamingMethodId >=", value, "fileNamingMethodId");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdLessThan(Integer value) {
            addCriterion("FileNamingMethodId <", value, "fileNamingMethodId");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdLessThanOrEqualTo(Integer value) {
            addCriterion("FileNamingMethodId <=", value, "fileNamingMethodId");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdIn(List<Integer> values) {
            addCriterion("FileNamingMethodId in", values, "fileNamingMethodId");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdNotIn(List<Integer> values) {
            addCriterion("FileNamingMethodId not in", values, "fileNamingMethodId");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdBetween(Integer value1, Integer value2) {
            addCriterion("FileNamingMethodId between", value1, value2, "fileNamingMethodId");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FileNamingMethodId not between", value1, value2, "fileNamingMethodId");
            return (Criteria) this;
        }

        public Criteria andDestinationNameIsNull() {
            addCriterion("DestinationName is null");
            return (Criteria) this;
        }

        public Criteria andDestinationNameIsNotNull() {
            addCriterion("DestinationName is not null");
            return (Criteria) this;
        }

        public Criteria andDestinationNameEqualTo(String value) {
            addCriterion("DestinationName =", value, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameNotEqualTo(String value) {
            addCriterion("DestinationName <>", value, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameGreaterThan(String value) {
            addCriterion("DestinationName >", value, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameGreaterThanOrEqualTo(String value) {
            addCriterion("DestinationName >=", value, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameLessThan(String value) {
            addCriterion("DestinationName <", value, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameLessThanOrEqualTo(String value) {
            addCriterion("DestinationName <=", value, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameLike(String value) {
            addCriterion("DestinationName like", value, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameNotLike(String value) {
            addCriterion("DestinationName not like", value, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameIn(List<String> values) {
            addCriterion("DestinationName in", values, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameNotIn(List<String> values) {
            addCriterion("DestinationName not in", values, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameBetween(String value1, String value2) {
            addCriterion("DestinationName between", value1, value2, "destinationName");
            return (Criteria) this;
        }

        public Criteria andDestinationNameNotBetween(String value1, String value2) {
            addCriterion("DestinationName not between", value1, value2, "destinationName");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIsNull() {
            addCriterion("FileNamingMethod is null");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIsNotNull() {
            addCriterion("FileNamingMethod is not null");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodEqualTo(String value) {
            addCriterion("FileNamingMethod =", value, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodNotEqualTo(String value) {
            addCriterion("FileNamingMethod <>", value, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodGreaterThan(String value) {
            addCriterion("FileNamingMethod >", value, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodGreaterThanOrEqualTo(String value) {
            addCriterion("FileNamingMethod >=", value, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodLessThan(String value) {
            addCriterion("FileNamingMethod <", value, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodLessThanOrEqualTo(String value) {
            addCriterion("FileNamingMethod <=", value, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodLike(String value) {
            addCriterion("FileNamingMethod like", value, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodNotLike(String value) {
            addCriterion("FileNamingMethod not like", value, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodIn(List<String> values) {
            addCriterion("FileNamingMethod in", values, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodNotIn(List<String> values) {
            addCriterion("FileNamingMethod not in", values, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodBetween(String value1, String value2) {
            addCriterion("FileNamingMethod between", value1, value2, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andFileNamingMethodNotBetween(String value1, String value2) {
            addCriterion("FileNamingMethod not between", value1, value2, "fileNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodIsNull() {
            addCriterion("ExtensionNamingMethod is null");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodIsNotNull() {
            addCriterion("ExtensionNamingMethod is not null");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodEqualTo(String value) {
            addCriterion("ExtensionNamingMethod =", value, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodNotEqualTo(String value) {
            addCriterion("ExtensionNamingMethod <>", value, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodGreaterThan(String value) {
            addCriterion("ExtensionNamingMethod >", value, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodGreaterThanOrEqualTo(String value) {
            addCriterion("ExtensionNamingMethod >=", value, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodLessThan(String value) {
            addCriterion("ExtensionNamingMethod <", value, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodLessThanOrEqualTo(String value) {
            addCriterion("ExtensionNamingMethod <=", value, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodLike(String value) {
            addCriterion("ExtensionNamingMethod like", value, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodNotLike(String value) {
            addCriterion("ExtensionNamingMethod not like", value, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodIn(List<String> values) {
            addCriterion("ExtensionNamingMethod in", values, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodNotIn(List<String> values) {
            addCriterion("ExtensionNamingMethod not in", values, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodBetween(String value1, String value2) {
            addCriterion("ExtensionNamingMethod between", value1, value2, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andExtensionNamingMethodNotBetween(String value1, String value2) {
            addCriterion("ExtensionNamingMethod not between", value1, value2, "extensionNamingMethod");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdIsNull() {
            addCriterion("WatchFolderId is null");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdIsNotNull() {
            addCriterion("WatchFolderId is not null");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdEqualTo(String value) {
            addCriterion("WatchFolderId =", value, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdNotEqualTo(String value) {
            addCriterion("WatchFolderId <>", value, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdGreaterThan(String value) {
            addCriterion("WatchFolderId >", value, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdGreaterThanOrEqualTo(String value) {
            addCriterion("WatchFolderId >=", value, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdLessThan(String value) {
            addCriterion("WatchFolderId <", value, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdLessThanOrEqualTo(String value) {
            addCriterion("WatchFolderId <=", value, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdLike(String value) {
            addCriterion("WatchFolderId like", value, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdNotLike(String value) {
            addCriterion("WatchFolderId not like", value, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdIn(List<String> values) {
            addCriterion("WatchFolderId in", values, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdNotIn(List<String> values) {
            addCriterion("WatchFolderId not in", values, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdBetween(String value1, String value2) {
            addCriterion("WatchFolderId between", value1, value2, "watchFolderId");
            return (Criteria) this;
        }

        public Criteria andWatchFolderIdNotBetween(String value1, String value2) {
            addCriterion("WatchFolderId not between", value1, value2, "watchFolderId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Destinations
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 01 09:09:58 PST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}