package com.smedia.sqzserver.dataservice.model.base;

import java.util.Date;

public class JobQueues {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JobQueues.QueueId
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    private String queueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JobQueues.Name
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JobQueues.Description
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JobQueues.Created
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JobQueues.Modified
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JobQueues.QueueId
     *
     * @return the value of JobQueues.QueueId
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    public String getQueueId() {
        return queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JobQueues.QueueId
     *
     * @param queueId the value for JobQueues.QueueId
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    public void setQueueId(String queueId) {
        this.queueId = queueId == null ? null : queueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JobQueues.Name
     *
     * @return the value of JobQueues.Name
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JobQueues.Name
     *
     * @param name the value for JobQueues.Name
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JobQueues.Description
     *
     * @return the value of JobQueues.Description
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JobQueues.Description
     *
     * @param description the value for JobQueues.Description
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JobQueues.Created
     *
     * @return the value of JobQueues.Created
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JobQueues.Created
     *
     * @param created the value for JobQueues.Created
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JobQueues.Modified
     *
     * @return the value of JobQueues.Modified
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JobQueues.Modified
     *
     * @param modified the value for JobQueues.Modified
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}