package com.smedia.sqzserver.dataservice.model.base;

public class OutputMetadata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OutputMetadata.OutputMetadataId
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    private String outputMetadataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OutputMetadata.OutputId
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    private String outputId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OutputMetadata.TrackName
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    private String trackName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OutputMetadata.TrackType
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    private String trackType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OutputMetadata.Name
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OutputMetadata.Value
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OutputMetadata.OutputMetadataId
     *
     * @return the value of OutputMetadata.OutputMetadataId
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public String getOutputMetadataId() {
        return outputMetadataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OutputMetadata.OutputMetadataId
     *
     * @param outputMetadataId the value for OutputMetadata.OutputMetadataId
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public void setOutputMetadataId(String outputMetadataId) {
        this.outputMetadataId = outputMetadataId == null ? null : outputMetadataId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OutputMetadata.OutputId
     *
     * @return the value of OutputMetadata.OutputId
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public String getOutputId() {
        return outputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OutputMetadata.OutputId
     *
     * @param outputId the value for OutputMetadata.OutputId
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public void setOutputId(String outputId) {
        this.outputId = outputId == null ? null : outputId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OutputMetadata.TrackName
     *
     * @return the value of OutputMetadata.TrackName
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public String getTrackName() {
        return trackName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OutputMetadata.TrackName
     *
     * @param trackName the value for OutputMetadata.TrackName
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public void setTrackName(String trackName) {
        this.trackName = trackName == null ? null : trackName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OutputMetadata.TrackType
     *
     * @return the value of OutputMetadata.TrackType
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public String getTrackType() {
        return trackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OutputMetadata.TrackType
     *
     * @param trackType the value for OutputMetadata.TrackType
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public void setTrackType(String trackType) {
        this.trackType = trackType == null ? null : trackType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OutputMetadata.Name
     *
     * @return the value of OutputMetadata.Name
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OutputMetadata.Name
     *
     * @param name the value for OutputMetadata.Name
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OutputMetadata.Value
     *
     * @return the value of OutputMetadata.Value
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OutputMetadata.Value
     *
     * @param value the value for OutputMetadata.Value
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}