package com.smedia.sqzserver.dataservice.model.base;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Source {
	
	public Source() {
		locationTypeId = 1;
		fileSize = 0L;
	}
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.SourceId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.JobId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.LocationTypeId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private Integer locationTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.URI
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String URI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.FileName
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.SSSBucket
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String SSSBucket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.CredentialId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String credentialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.UserName
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.Password
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.Salt
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.FileSize
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.Created
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.Modified
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.WatchFolderId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String watchFolderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sources.WatermarkImageUri
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    private String watermarkImageUri;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.SourceId
     *
     * @return the value of Sources.SourceId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.SourceId
     *
     * @param sourceId the value for Sources.SourceId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.JobId
     *
     * @return the value of Sources.JobId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.JobId
     *
     * @param jobId the value for Sources.JobId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.LocationTypeId
     *
     * @return the value of Sources.LocationTypeId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public Integer getLocationTypeId() {
        return locationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.LocationTypeId
     *
     * @param locationTypeId the value for Sources.LocationTypeId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setLocationTypeId(Integer locationTypeId) {
        this.locationTypeId = locationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.URI
     *
     * @return the value of Sources.URI
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getURI() {
        return URI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.URI
     *
     * @param URI the value for Sources.URI
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setURI(String URI) {
        this.URI = URI == null ? null : URI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.FileName
     *
     * @return the value of Sources.FileName
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.FileName
     *
     * @param fileName the value for Sources.FileName
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.SSSBucket
     *
     * @return the value of Sources.SSSBucket
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getSSSBucket() {
        return SSSBucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.SSSBucket
     *
     * @param SSSBucket the value for Sources.SSSBucket
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setSSSBucket(String SSSBucket) {
        this.SSSBucket = SSSBucket == null ? null : SSSBucket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.CredentialId
     *
     * @return the value of Sources.CredentialId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getCredentialId() {
        return credentialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.CredentialId
     *
     * @param credentialId the value for Sources.CredentialId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setCredentialId(String credentialId) {
        this.credentialId = credentialId == null ? null : credentialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.UserName
     *
     * @return the value of Sources.UserName
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.UserName
     *
     * @param userName the value for Sources.UserName
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.Password
     *
     * @return the value of Sources.Password
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.Password
     *
     * @param password the value for Sources.Password
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.Salt
     *
     * @return the value of Sources.Salt
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.Salt
     *
     * @param salt the value for Sources.Salt
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.FileSize
     *
     * @return the value of Sources.FileSize
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.FileSize
     *
     * @param fileSize the value for Sources.FileSize
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.Created
     *
     * @return the value of Sources.Created
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.Created
     *
     * @param created the value for Sources.Created
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.Modified
     *
     * @return the value of Sources.Modified
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.Modified
     *
     * @param modified the value for Sources.Modified
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.WatchFolderId
     *
     * @return the value of Sources.WatchFolderId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getWatchFolderId() {
        return watchFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.WatchFolderId
     *
     * @param watchFolderId the value for Sources.WatchFolderId
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setWatchFolderId(String watchFolderId) {
        this.watchFolderId = watchFolderId == null ? null : watchFolderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sources.WatermarkImageUri
     *
     * @return the value of Sources.WatermarkImageUri
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getWatermarkImageUri() {
        return watermarkImageUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sources.WatermarkImageUri
     *
     * @param watermarkImageUri the value for Sources.WatermarkImageUri
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setWatermarkImageUri(String watermarkImageUri) {
        this.watermarkImageUri = watermarkImageUri == null ? null : watermarkImageUri.trim();
    }
}