package com.smedia.sqzserver.dataservice.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public StatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStatusIdIsNull() {
            addCriterion("StatusId is null");
            return (Criteria) this;
        }

        public Criteria andStatusIdIsNotNull() {
            addCriterion("StatusId is not null");
            return (Criteria) this;
        }

        public Criteria andStatusIdEqualTo(String value) {
            addCriterion("StatusId =", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotEqualTo(String value) {
            addCriterion("StatusId <>", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdGreaterThan(String value) {
            addCriterion("StatusId >", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdGreaterThanOrEqualTo(String value) {
            addCriterion("StatusId >=", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLessThan(String value) {
            addCriterion("StatusId <", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLessThanOrEqualTo(String value) {
            addCriterion("StatusId <=", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLike(String value) {
            addCriterion("StatusId like", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotLike(String value) {
            addCriterion("StatusId not like", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdIn(List<String> values) {
            addCriterion("StatusId in", values, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotIn(List<String> values) {
            addCriterion("StatusId not in", values, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdBetween(String value1, String value2) {
            addCriterion("StatusId between", value1, value2, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotBetween(String value1, String value2) {
            addCriterion("StatusId not between", value1, value2, "statusId");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNull() {
            addCriterion("JobId is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("JobId is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(String value) {
            addCriterion("JobId =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(String value) {
            addCriterion("JobId <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(String value) {
            addCriterion("JobId >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(String value) {
            addCriterion("JobId >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(String value) {
            addCriterion("JobId <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(String value) {
            addCriterion("JobId <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLike(String value) {
            addCriterion("JobId like", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotLike(String value) {
            addCriterion("JobId not like", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<String> values) {
            addCriterion("JobId in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<String> values) {
            addCriterion("JobId not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(String value1, String value2) {
            addCriterion("JobId between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(String value1, String value2) {
            addCriterion("JobId not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdIsNull() {
            addCriterion("StatusStateId is null");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdIsNotNull() {
            addCriterion("StatusStateId is not null");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdEqualTo(Integer value) {
            addCriterion("StatusStateId =", value, "statusStateId");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdNotEqualTo(Integer value) {
            addCriterion("StatusStateId <>", value, "statusStateId");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdGreaterThan(Integer value) {
            addCriterion("StatusStateId >", value, "statusStateId");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("StatusStateId >=", value, "statusStateId");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdLessThan(Integer value) {
            addCriterion("StatusStateId <", value, "statusStateId");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdLessThanOrEqualTo(Integer value) {
            addCriterion("StatusStateId <=", value, "statusStateId");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdIn(List<Integer> values) {
            addCriterion("StatusStateId in", values, "statusStateId");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdNotIn(List<Integer> values) {
            addCriterion("StatusStateId not in", values, "statusStateId");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdBetween(Integer value1, Integer value2) {
            addCriterion("StatusStateId between", value1, value2, "statusStateId");
            return (Criteria) this;
        }

        public Criteria andStatusStateIdNotBetween(Integer value1, Integer value2) {
            addCriterion("StatusStateId not between", value1, value2, "statusStateId");
            return (Criteria) this;
        }

        public Criteria andTimeStartedIsNull() {
            addCriterion("TimeStarted is null");
            return (Criteria) this;
        }

        public Criteria andTimeStartedIsNotNull() {
            addCriterion("TimeStarted is not null");
            return (Criteria) this;
        }

        public Criteria andTimeStartedEqualTo(Date value) {
            addCriterion("TimeStarted =", value, "timeStarted");
            return (Criteria) this;
        }

        public Criteria andTimeStartedNotEqualTo(Date value) {
            addCriterion("TimeStarted <>", value, "timeStarted");
            return (Criteria) this;
        }

        public Criteria andTimeStartedGreaterThan(Date value) {
            addCriterion("TimeStarted >", value, "timeStarted");
            return (Criteria) this;
        }

        public Criteria andTimeStartedGreaterThanOrEqualTo(Date value) {
            addCriterion("TimeStarted >=", value, "timeStarted");
            return (Criteria) this;
        }

        public Criteria andTimeStartedLessThan(Date value) {
            addCriterion("TimeStarted <", value, "timeStarted");
            return (Criteria) this;
        }

        public Criteria andTimeStartedLessThanOrEqualTo(Date value) {
            addCriterion("TimeStarted <=", value, "timeStarted");
            return (Criteria) this;
        }

        public Criteria andTimeStartedIn(List<Date> values) {
            addCriterion("TimeStarted in", values, "timeStarted");
            return (Criteria) this;
        }

        public Criteria andTimeStartedNotIn(List<Date> values) {
            addCriterion("TimeStarted not in", values, "timeStarted");
            return (Criteria) this;
        }

        public Criteria andTimeStartedBetween(Date value1, Date value2) {
            addCriterion("TimeStarted between", value1, value2, "timeStarted");
            return (Criteria) this;
        }

        public Criteria andTimeStartedNotBetween(Date value1, Date value2) {
            addCriterion("TimeStarted not between", value1, value2, "timeStarted");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedIsNull() {
            addCriterion("TimeFinished is null");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedIsNotNull() {
            addCriterion("TimeFinished is not null");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedEqualTo(Date value) {
            addCriterion("TimeFinished =", value, "timeFinished");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedNotEqualTo(Date value) {
            addCriterion("TimeFinished <>", value, "timeFinished");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedGreaterThan(Date value) {
            addCriterion("TimeFinished >", value, "timeFinished");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedGreaterThanOrEqualTo(Date value) {
            addCriterion("TimeFinished >=", value, "timeFinished");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedLessThan(Date value) {
            addCriterion("TimeFinished <", value, "timeFinished");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedLessThanOrEqualTo(Date value) {
            addCriterion("TimeFinished <=", value, "timeFinished");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedIn(List<Date> values) {
            addCriterion("TimeFinished in", values, "timeFinished");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedNotIn(List<Date> values) {
            addCriterion("TimeFinished not in", values, "timeFinished");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedBetween(Date value1, Date value2) {
            addCriterion("TimeFinished between", value1, value2, "timeFinished");
            return (Criteria) this;
        }

        public Criteria andTimeFinishedNotBetween(Date value1, Date value2) {
            addCriterion("TimeFinished not between", value1, value2, "timeFinished");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteIsNull() {
            addCriterion("PercentComplete is null");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteIsNotNull() {
            addCriterion("PercentComplete is not null");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteEqualTo(Float value) {
            addCriterion("PercentComplete =", value, "percentComplete");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteNotEqualTo(Float value) {
            addCriterion("PercentComplete <>", value, "percentComplete");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteGreaterThan(Float value) {
            addCriterion("PercentComplete >", value, "percentComplete");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteGreaterThanOrEqualTo(Float value) {
            addCriterion("PercentComplete >=", value, "percentComplete");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteLessThan(Float value) {
            addCriterion("PercentComplete <", value, "percentComplete");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteLessThanOrEqualTo(Float value) {
            addCriterion("PercentComplete <=", value, "percentComplete");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteIn(List<Float> values) {
            addCriterion("PercentComplete in", values, "percentComplete");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteNotIn(List<Float> values) {
            addCriterion("PercentComplete not in", values, "percentComplete");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteBetween(Float value1, Float value2) {
            addCriterion("PercentComplete between", value1, value2, "percentComplete");
            return (Criteria) this;
        }

        public Criteria andPercentCompleteNotBetween(Float value1, Float value2) {
            addCriterion("PercentComplete not between", value1, value2, "percentComplete");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIsNull() {
            addCriterion("ErrorCode is null");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIsNotNull() {
            addCriterion("ErrorCode is not null");
            return (Criteria) this;
        }

        public Criteria andErrorCodeEqualTo(String value) {
            addCriterion("ErrorCode =", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotEqualTo(String value) {
            addCriterion("ErrorCode <>", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeGreaterThan(String value) {
            addCriterion("ErrorCode >", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ErrorCode >=", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLessThan(String value) {
            addCriterion("ErrorCode <", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLessThanOrEqualTo(String value) {
            addCriterion("ErrorCode <=", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLike(String value) {
            addCriterion("ErrorCode like", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotLike(String value) {
            addCriterion("ErrorCode not like", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIn(List<String> values) {
            addCriterion("ErrorCode in", values, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotIn(List<String> values) {
            addCriterion("ErrorCode not in", values, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeBetween(String value1, String value2) {
            addCriterion("ErrorCode between", value1, value2, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotBetween(String value1, String value2) {
            addCriterion("ErrorCode not between", value1, value2, "errorCode");
            return (Criteria) this;
        }

        public Criteria andMessageIsNull() {
            addCriterion("Message is null");
            return (Criteria) this;
        }

        public Criteria andMessageIsNotNull() {
            addCriterion("Message is not null");
            return (Criteria) this;
        }

        public Criteria andMessageEqualTo(String value) {
            addCriterion("Message =", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotEqualTo(String value) {
            addCriterion("Message <>", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThan(String value) {
            addCriterion("Message >", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThanOrEqualTo(String value) {
            addCriterion("Message >=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThan(String value) {
            addCriterion("Message <", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThanOrEqualTo(String value) {
            addCriterion("Message <=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLike(String value) {
            addCriterion("Message like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotLike(String value) {
            addCriterion("Message not like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageIn(List<String> values) {
            addCriterion("Message in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotIn(List<String> values) {
            addCriterion("Message not in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageBetween(String value1, String value2) {
            addCriterion("Message between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotBetween(String value1, String value2) {
            addCriterion("Message not between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andRetryCountIsNull() {
            addCriterion("RetryCount is null");
            return (Criteria) this;
        }

        public Criteria andRetryCountIsNotNull() {
            addCriterion("RetryCount is not null");
            return (Criteria) this;
        }

        public Criteria andRetryCountEqualTo(Short value) {
            addCriterion("RetryCount =", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotEqualTo(Short value) {
            addCriterion("RetryCount <>", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountGreaterThan(Short value) {
            addCriterion("RetryCount >", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountGreaterThanOrEqualTo(Short value) {
            addCriterion("RetryCount >=", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountLessThan(Short value) {
            addCriterion("RetryCount <", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountLessThanOrEqualTo(Short value) {
            addCriterion("RetryCount <=", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountIn(List<Short> values) {
            addCriterion("RetryCount in", values, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotIn(List<Short> values) {
            addCriterion("RetryCount not in", values, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountBetween(Short value1, Short value2) {
            addCriterion("RetryCount between", value1, value2, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotBetween(Short value1, Short value2) {
            addCriterion("RetryCount not between", value1, value2, "retryCount");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdIsNull() {
            addCriterion("JobPresetId is null");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdIsNotNull() {
            addCriterion("JobPresetId is not null");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdEqualTo(String value) {
            addCriterion("JobPresetId =", value, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdNotEqualTo(String value) {
            addCriterion("JobPresetId <>", value, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdGreaterThan(String value) {
            addCriterion("JobPresetId >", value, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdGreaterThanOrEqualTo(String value) {
            addCriterion("JobPresetId >=", value, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdLessThan(String value) {
            addCriterion("JobPresetId <", value, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdLessThanOrEqualTo(String value) {
            addCriterion("JobPresetId <=", value, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdLike(String value) {
            addCriterion("JobPresetId like", value, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdNotLike(String value) {
            addCriterion("JobPresetId not like", value, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdIn(List<String> values) {
            addCriterion("JobPresetId in", values, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdNotIn(List<String> values) {
            addCriterion("JobPresetId not in", values, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdBetween(String value1, String value2) {
            addCriterion("JobPresetId between", value1, value2, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andJobPresetIdNotBetween(String value1, String value2) {
            addCriterion("JobPresetId not between", value1, value2, "jobPresetId");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("Modified is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("Modified is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("Modified =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("Modified <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("Modified >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("Modified >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("Modified <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("Modified <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("Modified in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("Modified not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("Modified between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("Modified not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("Created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("Created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("Created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("Created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("Created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("Created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("Created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("Created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("Created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("Created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("Created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("Created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andDestinationIdIsNull() {
            addCriterion("DestinationId is null");
            return (Criteria) this;
        }

        public Criteria andDestinationIdIsNotNull() {
            addCriterion("DestinationId is not null");
            return (Criteria) this;
        }

        public Criteria andDestinationIdEqualTo(String value) {
            addCriterion("DestinationId =", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdNotEqualTo(String value) {
            addCriterion("DestinationId <>", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdGreaterThan(String value) {
            addCriterion("DestinationId >", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdGreaterThanOrEqualTo(String value) {
            addCriterion("DestinationId >=", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdLessThan(String value) {
            addCriterion("DestinationId <", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdLessThanOrEqualTo(String value) {
            addCriterion("DestinationId <=", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdLike(String value) {
            addCriterion("DestinationId like", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdNotLike(String value) {
            addCriterion("DestinationId not like", value, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdIn(List<String> values) {
            addCriterion("DestinationId in", values, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdNotIn(List<String> values) {
            addCriterion("DestinationId not in", values, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdBetween(String value1, String value2) {
            addCriterion("DestinationId between", value1, value2, "destinationId");
            return (Criteria) this;
        }

        public Criteria andDestinationIdNotBetween(String value1, String value2) {
            addCriterion("DestinationId not between", value1, value2, "destinationId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Status
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 01 09:09:58 PST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}