package com.smedia.sqzserver.dataservice.model.base;

public class WatchFolderPlugin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPlugins.PluginId
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    private String pluginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPlugins.WatchFolderId
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    private String watchFolderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPlugins.PhaseType
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    private String phaseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPlugins.PluginType
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    private String pluginType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPlugins.PluginId
     *
     * @return the value of WatchFolderPlugins.PluginId
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    public String getPluginId() {
        return pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPlugins.PluginId
     *
     * @param pluginId the value for WatchFolderPlugins.PluginId
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    public void setPluginId(String pluginId) {
        this.pluginId = pluginId == null ? null : pluginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPlugins.WatchFolderId
     *
     * @return the value of WatchFolderPlugins.WatchFolderId
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    public String getWatchFolderId() {
        return watchFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPlugins.WatchFolderId
     *
     * @param watchFolderId the value for WatchFolderPlugins.WatchFolderId
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    public void setWatchFolderId(String watchFolderId) {
        this.watchFolderId = watchFolderId == null ? null : watchFolderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPlugins.PhaseType
     *
     * @return the value of WatchFolderPlugins.PhaseType
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    public String getPhaseType() {
        return phaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPlugins.PhaseType
     *
     * @param phaseType the value for WatchFolderPlugins.PhaseType
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    public void setPhaseType(String phaseType) {
        this.phaseType = phaseType == null ? null : phaseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPlugins.PluginType
     *
     * @return the value of WatchFolderPlugins.PluginType
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    public String getPluginType() {
        return pluginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPlugins.PluginType
     *
     * @param pluginType the value for WatchFolderPlugins.PluginType
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    public void setPluginType(String pluginType) {
        this.pluginType = pluginType == null ? null : pluginType.trim();
    }
}