package com.smedia.sqzserver.dataservice.model.base;

import java.util.Date;

public class WatchFolderPreset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPresets.WatchFolderPresetId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String watchFolderPresetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPresets.WatchFolderId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String watchFolderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPresets.PresetId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String presetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPresets.URI
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String URI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPresets.InPoint
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Double inPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPresets.OutPoint
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Double outPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPresets.Created
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPresets.Modified
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPresets.Name
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolderPresets.XmlData
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String xmlData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPresets.WatchFolderPresetId
     *
     * @return the value of WatchFolderPresets.WatchFolderPresetId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getWatchFolderPresetId() {
        return watchFolderPresetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPresets.WatchFolderPresetId
     *
     * @param watchFolderPresetId the value for WatchFolderPresets.WatchFolderPresetId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setWatchFolderPresetId(String watchFolderPresetId) {
        this.watchFolderPresetId = watchFolderPresetId == null ? null : watchFolderPresetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPresets.WatchFolderId
     *
     * @return the value of WatchFolderPresets.WatchFolderId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getWatchFolderId() {
        return watchFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPresets.WatchFolderId
     *
     * @param watchFolderId the value for WatchFolderPresets.WatchFolderId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setWatchFolderId(String watchFolderId) {
        this.watchFolderId = watchFolderId == null ? null : watchFolderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPresets.PresetId
     *
     * @return the value of WatchFolderPresets.PresetId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getPresetId() {
        return presetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPresets.PresetId
     *
     * @param presetId the value for WatchFolderPresets.PresetId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setPresetId(String presetId) {
        this.presetId = presetId == null ? null : presetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPresets.URI
     *
     * @return the value of WatchFolderPresets.URI
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getURI() {
        return URI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPresets.URI
     *
     * @param URI the value for WatchFolderPresets.URI
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setURI(String URI) {
        this.URI = URI == null ? null : URI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPresets.InPoint
     *
     * @return the value of WatchFolderPresets.InPoint
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Double getInPoint() {
        return inPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPresets.InPoint
     *
     * @param inPoint the value for WatchFolderPresets.InPoint
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setInPoint(Double inPoint) {
        this.inPoint = inPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPresets.OutPoint
     *
     * @return the value of WatchFolderPresets.OutPoint
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Double getOutPoint() {
        return outPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPresets.OutPoint
     *
     * @param outPoint the value for WatchFolderPresets.OutPoint
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setOutPoint(Double outPoint) {
        this.outPoint = outPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPresets.Created
     *
     * @return the value of WatchFolderPresets.Created
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPresets.Created
     *
     * @param created the value for WatchFolderPresets.Created
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPresets.Modified
     *
     * @return the value of WatchFolderPresets.Modified
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPresets.Modified
     *
     * @param modified the value for WatchFolderPresets.Modified
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPresets.Name
     *
     * @return the value of WatchFolderPresets.Name
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPresets.Name
     *
     * @param name the value for WatchFolderPresets.Name
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolderPresets.XmlData
     *
     * @return the value of WatchFolderPresets.XmlData
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getXmlData() {
        return xmlData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolderPresets.XmlData
     *
     * @param xmlData the value for WatchFolderPresets.XmlData
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setXmlData(String xmlData) {
        this.xmlData = xmlData == null ? null : xmlData.trim();
    }
}