package com.smedia.sqzserver.dataservice.model.base;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class WatchFolder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.WatchFolderId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String watchFolderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.Name
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.LastScanStart
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Date lastScanStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.LastScanEnd
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Date lastScanEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.LastScanNumberJobsCreated
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Integer lastScanNumberJobsCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.LastScanServerName
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String lastScanServerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.CurrentScanServerId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String currentScanServerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.CurrentScanStart
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Date currentScanStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.LastScanOldestFileTimeTicks
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Long lastScanOldestFileTimeTicks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.LastScanNewestFileTimeTicks
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Long lastScanNewestFileTimeTicks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.Enabled
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.Deleted
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.Created
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.Modified
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.QueueId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String queueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.Message
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WatchFolders.DeepScan
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    private Boolean deepScan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.WatchFolderId
     *
     * @return the value of WatchFolders.WatchFolderId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getWatchFolderId() {
        return watchFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.WatchFolderId
     *
     * @param watchFolderId the value for WatchFolders.WatchFolderId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setWatchFolderId(String watchFolderId) {
        this.watchFolderId = watchFolderId == null ? null : watchFolderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.Name
     *
     * @return the value of WatchFolders.Name
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.Name
     *
     * @param name the value for WatchFolders.Name
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.LastScanStart
     *
     * @return the value of WatchFolders.LastScanStart
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Date getLastScanStart() {
        return lastScanStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.LastScanStart
     *
     * @param lastScanStart the value for WatchFolders.LastScanStart
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setLastScanStart(Date lastScanStart) {
        this.lastScanStart = lastScanStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.LastScanEnd
     *
     * @return the value of WatchFolders.LastScanEnd
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Date getLastScanEnd() {
        return lastScanEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.LastScanEnd
     *
     * @param lastScanEnd the value for WatchFolders.LastScanEnd
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setLastScanEnd(Date lastScanEnd) {
        this.lastScanEnd = lastScanEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.LastScanNumberJobsCreated
     *
     * @return the value of WatchFolders.LastScanNumberJobsCreated
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Integer getLastScanNumberJobsCreated() {
        return lastScanNumberJobsCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.LastScanNumberJobsCreated
     *
     * @param lastScanNumberJobsCreated the value for WatchFolders.LastScanNumberJobsCreated
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setLastScanNumberJobsCreated(Integer lastScanNumberJobsCreated) {
        this.lastScanNumberJobsCreated = lastScanNumberJobsCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.LastScanServerName
     *
     * @return the value of WatchFolders.LastScanServerName
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getLastScanServerName() {
        return lastScanServerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.LastScanServerName
     *
     * @param lastScanServerName the value for WatchFolders.LastScanServerName
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setLastScanServerName(String lastScanServerName) {
        this.lastScanServerName = lastScanServerName == null ? null : lastScanServerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.CurrentScanServerId
     *
     * @return the value of WatchFolders.CurrentScanServerId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getCurrentScanServerId() {
        return currentScanServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.CurrentScanServerId
     *
     * @param currentScanServerId the value for WatchFolders.CurrentScanServerId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setCurrentScanServerId(String currentScanServerId) {
        this.currentScanServerId = currentScanServerId == null ? null : currentScanServerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.CurrentScanStart
     *
     * @return the value of WatchFolders.CurrentScanStart
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Date getCurrentScanStart() {
        return currentScanStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.CurrentScanStart
     *
     * @param currentScanStart the value for WatchFolders.CurrentScanStart
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setCurrentScanStart(Date currentScanStart) {
        this.currentScanStart = currentScanStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.LastScanOldestFileTimeTicks
     *
     * @return the value of WatchFolders.LastScanOldestFileTimeTicks
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Long getLastScanOldestFileTimeTicks() {
        return lastScanOldestFileTimeTicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.LastScanOldestFileTimeTicks
     *
     * @param lastScanOldestFileTimeTicks the value for WatchFolders.LastScanOldestFileTimeTicks
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setLastScanOldestFileTimeTicks(Long lastScanOldestFileTimeTicks) {
        this.lastScanOldestFileTimeTicks = lastScanOldestFileTimeTicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.LastScanNewestFileTimeTicks
     *
     * @return the value of WatchFolders.LastScanNewestFileTimeTicks
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Long getLastScanNewestFileTimeTicks() {
        return lastScanNewestFileTimeTicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.LastScanNewestFileTimeTicks
     *
     * @param lastScanNewestFileTimeTicks the value for WatchFolders.LastScanNewestFileTimeTicks
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setLastScanNewestFileTimeTicks(Long lastScanNewestFileTimeTicks) {
        this.lastScanNewestFileTimeTicks = lastScanNewestFileTimeTicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.Enabled
     *
     * @return the value of WatchFolders.Enabled
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.Enabled
     *
     * @param enabled the value for WatchFolders.Enabled
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.Deleted
     *
     * @return the value of WatchFolders.Deleted
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.Deleted
     *
     * @param deleted the value for WatchFolders.Deleted
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.Created
     *
     * @return the value of WatchFolders.Created
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.Created
     *
     * @param created the value for WatchFolders.Created
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.Modified
     *
     * @return the value of WatchFolders.Modified
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.Modified
     *
     * @param modified the value for WatchFolders.Modified
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.QueueId
     *
     * @return the value of WatchFolders.QueueId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getQueueId() {
        return queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.QueueId
     *
     * @param queueId the value for WatchFolders.QueueId
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setQueueId(String queueId) {
        this.queueId = queueId == null ? null : queueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.Message
     *
     * @return the value of WatchFolders.Message
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.Message
     *
     * @param message the value for WatchFolders.Message
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WatchFolders.DeepScan
     *
     * @return the value of WatchFolders.DeepScan
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public Boolean getDeepScan() {
        return deepScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WatchFolders.DeepScan
     *
     * @param deepScan the value for WatchFolders.DeepScan
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    public void setDeepScan(Boolean deepScan) {
        this.deepScan = deepScan;
    }
}