package com.smedia.sqzserver.dataservice.model.base;

import java.util.Date;

public class WorkflowCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowCategories.workflowCategoryId
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    private String workflowCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowCategories.Name
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowCategories.Description
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowCategories.Created
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowCategories.Modified
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowCategories.workflowCategoryId
     *
     * @return the value of workflowCategories.workflowCategoryId
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    public String getWorkflowCategoryId() {
        return workflowCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowCategories.workflowCategoryId
     *
     * @param workflowCategoryId the value for workflowCategories.workflowCategoryId
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    public void setWorkflowCategoryId(String workflowCategoryId) {
        this.workflowCategoryId = workflowCategoryId == null ? null : workflowCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowCategories.Name
     *
     * @return the value of workflowCategories.Name
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowCategories.Name
     *
     * @param name the value for workflowCategories.Name
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowCategories.Description
     *
     * @return the value of workflowCategories.Description
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowCategories.Description
     *
     * @param description the value for workflowCategories.Description
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowCategories.Created
     *
     * @return the value of workflowCategories.Created
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowCategories.Created
     *
     * @param created the value for workflowCategories.Created
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowCategories.Modified
     *
     * @return the value of workflowCategories.Modified
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowCategories.Modified
     *
     * @param modified the value for workflowCategories.Modified
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}