package com.smedia.sqzserver.dataservice.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smedia.sqzserver.dataservice.model.base.Destination;
import com.smedia.sqzserver.dataservice.model.base.DestinationExample;

public interface DestinationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int countByExample(DestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int deleteByExample(DestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int deleteByPrimaryKey(String destinationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int insert(Destination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int insertSelective(Destination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    List<Destination> selectByExample(DestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    Destination selectByPrimaryKey(String destinationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExampleSelective(@Param("record") Destination record, @Param("example") DestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExample(@Param("record") Destination record, @Param("example") DestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKeySelective(Destination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Destinations
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKey(Destination record);
}