package com.smedia.sqzserver.dataservice.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smedia.sqzserver.dataservice.model.base.Job;
import com.smedia.sqzserver.dataservice.model.base.JobExample;

public interface JobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int countByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int deleteByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int deleteByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    List<Job> selectByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    Job selectByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExampleSelective(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExample(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Jobs
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKey(Job record);
}