package com.smedia.sqzserver.dataservice.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smedia.sqzserver.dataservice.model.base.JobOutput;
import com.smedia.sqzserver.dataservice.model.base.JobOutputExample;

public interface JobOutputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int countByExample(JobOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int deleteByExample(JobOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int deleteByPrimaryKey(String outputId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int insert(JobOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int insertSelective(JobOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    List<JobOutput> selectByExample(JobOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    JobOutput selectByPrimaryKey(String outputId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int updateByExampleSelective(@Param("record") JobOutput record, @Param("example") JobOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int updateByExample(@Param("record") JobOutput record, @Param("example") JobOutputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int updateByPrimaryKeySelective(JobOutput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobOutput
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int updateByPrimaryKey(JobOutput record);
}