package com.smedia.sqzserver.dataservice.dao.base;

import com.smedia.sqzserver.dataservice.model.base.JobPreset;
import com.smedia.sqzserver.dataservice.model.base.JobPresetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobPresetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int countByExample(JobPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int deleteByExample(JobPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int deleteByPrimaryKey(String jobPresetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int insert(JobPreset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int insertSelective(JobPreset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    List<JobPreset> selectByExampleWithBLOBs(JobPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    List<JobPreset> selectByExample(JobPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    JobPreset selectByPrimaryKey(String jobPresetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int updateByExampleSelective(@Param("record") JobPreset record, @Param("example") JobPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int updateByExampleWithBLOBs(@Param("record") JobPreset record, @Param("example") JobPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int updateByExample(@Param("record") JobPreset record, @Param("example") JobPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int updateByPrimaryKeySelective(JobPreset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int updateByPrimaryKeyWithBLOBs(JobPreset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobPresets
     *
     * @mbggenerated Wed Apr 25 18:18:06 PDT 2012
     */
    int updateByPrimaryKey(JobPreset record);
}