package com.smedia.sqzserver.dataservice.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smedia.sqzserver.dataservice.model.base.JobQueues;
import com.smedia.sqzserver.dataservice.model.base.JobQueuesExample;

public interface JobQueuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    int countByExample(JobQueuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    int deleteByExample(JobQueuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    int deleteByPrimaryKey(String queueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    int insert(JobQueues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    int insertSelective(JobQueues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    List<JobQueues> selectByExample(JobQueuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    JobQueues selectByPrimaryKey(String queueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    int updateByExampleSelective(@Param("record") JobQueues record, @Param("example") JobQueuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    int updateByExample(@Param("record") JobQueues record, @Param("example") JobQueuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    int updateByPrimaryKeySelective(JobQueues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JobQueues
     *
     * @mbggenerated Fri Feb 10 14:15:10 MST 2012
     */
    int updateByPrimaryKey(JobQueues record);
}