package com.smedia.sqzserver.dataservice.dao.base;

import com.smedia.sqzserver.dataservice.model.base.LicenseKey;
import com.smedia.sqzserver.dataservice.model.base.LicenseKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LicenseKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    int countByExample(LicenseKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    int deleteByExample(LicenseKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    int deleteByPrimaryKey(String licenseKeyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    int insert(LicenseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    int insertSelective(LicenseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    List<LicenseKey> selectByExample(LicenseKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    LicenseKey selectByPrimaryKey(String licenseKeyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    int updateByExampleSelective(@Param("record") LicenseKey record, @Param("example") LicenseKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    int updateByExample(@Param("record") LicenseKey record, @Param("example") LicenseKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    int updateByPrimaryKeySelective(LicenseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LicenseKeys
     *
     * @mbggenerated Wed Jun 20 12:13:55 MDT 2012
     */
    int updateByPrimaryKey(LicenseKey record);
}