package com.smedia.sqzserver.dataservice.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smedia.sqzserver.dataservice.model.base.Metadata;
import com.smedia.sqzserver.dataservice.model.base.MetadataExample;

public interface MetadataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int countByExample(MetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int deleteByExample(MetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int deleteByPrimaryKey(String metadataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int insert(Metadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int insertSelective(Metadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    List<Metadata> selectByExample(MetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    Metadata selectByPrimaryKey(String metadataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int updateByExampleSelective(@Param("record") Metadata record, @Param("example") MetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int updateByExample(@Param("record") Metadata record, @Param("example") MetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int updateByPrimaryKeySelective(Metadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Metadata
     *
     * @mbggenerated Wed Jan 18 12:46:26 PST 2012
     */
    int updateByPrimaryKey(Metadata record);
}