package com.smedia.sqzserver.dataservice.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smedia.sqzserver.dataservice.model.base.Preset;
import com.smedia.sqzserver.dataservice.model.base.PresetExample;

public interface PresetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int countByExample(PresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int deleteByExample(PresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int deleteByPrimaryKey(String presetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int insert(Preset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int insertSelective(Preset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    List<Preset> selectByExampleWithBLOBs(PresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    List<Preset> selectByExample(PresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    Preset selectByPrimaryKey(String presetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExampleSelective(@Param("record") Preset record, @Param("example") PresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExampleWithBLOBs(@Param("record") Preset record, @Param("example") PresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExample(@Param("record") Preset record, @Param("example") PresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKeySelective(Preset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKeyWithBLOBs(Preset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Presets
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKey(Preset record);
    
    /**
     * @param category
     * @return
     */
    List<Preset> selectByCategory(String category);
    
    
    
    /**
     * @return
     */
    List<String> selectPresetCategories();
}