package com.smedia.sqzserver.dataservice.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smedia.sqzserver.dataservice.model.base.ServerQueue;
import com.smedia.sqzserver.dataservice.model.base.ServerQueueExample;

public interface ServerQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    int countByExample(ServerQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    int deleteByExample(ServerQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    int deleteByPrimaryKey(String serverQueueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    int insert(ServerQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    int insertSelective(ServerQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    List<ServerQueue> selectByExample(ServerQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    ServerQueue selectByPrimaryKey(String serverQueueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    int updateByExampleSelective(@Param("record") ServerQueue record, @Param("example") ServerQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    int updateByExample(@Param("record") ServerQueue record, @Param("example") ServerQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    int updateByPrimaryKeySelective(ServerQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serverqueues
     *
     * @mbggenerated Thu Jan 26 23:49:44 MST 2012
     */
    int updateByPrimaryKey(ServerQueue record);
}