package com.smedia.sqzserver.dataservice.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smedia.sqzserver.dataservice.model.base.ServerStates;
import com.smedia.sqzserver.dataservice.model.base.ServerStatesExample;

public interface ServerStatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    int countByExample(ServerStatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    int deleteByExample(ServerStatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    int deleteByPrimaryKey(Integer serverStateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    int insert(ServerStates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    int insertSelective(ServerStates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    List<ServerStates> selectByExample(ServerStatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    ServerStates selectByPrimaryKey(Integer serverStateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    int updateByExampleSelective(@Param("record") ServerStates record, @Param("example") ServerStatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    int updateByExample(@Param("record") ServerStates record, @Param("example") ServerStatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    int updateByPrimaryKeySelective(ServerStates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ServerStates
     *
     * @mbggenerated Sat Feb 11 22:55:25 MST 2012
     */
    int updateByPrimaryKey(ServerStates record);
}