package com.smedia.sqzserver.dataservice.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smedia.sqzserver.dataservice.model.base.Source;
import com.smedia.sqzserver.dataservice.model.base.SourceExample;

public interface SourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int countByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int deleteByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int deleteByPrimaryKey(String sourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int insert(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int insertSelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    List<Source> selectByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    Source selectByPrimaryKey(String sourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExampleSelective(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExample(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKeySelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sources
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKey(Source record);
}