package com.smedia.sqzserver.dataservice.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smedia.sqzserver.dataservice.model.base.Status;
import com.smedia.sqzserver.dataservice.model.base.StatusExample;

public interface StatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int countByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int deleteByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int deleteByPrimaryKey(String statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int insert(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int insertSelective(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    List<Status> selectByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    Status selectByPrimaryKey(String statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExampleSelective(@Param("record") Status record, @Param("example") StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByExample(@Param("record") Status record, @Param("example") StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKeySelective(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status
     *
     * @mbggenerated Sun Jan 01 09:09:58 PST 2012
     */
    int updateByPrimaryKey(Status record);
}