package com.smedia.sqzserver.dataservice.dao.base;

import com.smedia.sqzserver.dataservice.model.base.WatchFolderSource;
import com.smedia.sqzserver.dataservice.model.base.WatchFolderSourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatchFolderSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int countByExample(WatchFolderSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int deleteByExample(WatchFolderSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int deleteByPrimaryKey(String sourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int insert(WatchFolderSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int insertSelective(WatchFolderSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    List<WatchFolderSource> selectByExample(WatchFolderSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    WatchFolderSource selectByPrimaryKey(String sourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByExampleSelective(@Param("record") WatchFolderSource record, @Param("example") WatchFolderSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByExample(@Param("record") WatchFolderSource record, @Param("example") WatchFolderSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByPrimaryKeySelective(WatchFolderSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderSources
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByPrimaryKey(WatchFolderSource record);
}