package com.smedia.sqzserver.dataservice.dao.base;

import com.smedia.sqzserver.dataservice.model.base.WatchFolderAttr;
import com.smedia.sqzserver.dataservice.model.base.WatchFolderAttrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatchFolderAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int countByExample(WatchFolderAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int deleteByExample(WatchFolderAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int deleteByPrimaryKey(String attributeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int insert(WatchFolderAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int insertSelective(WatchFolderAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    List<WatchFolderAttr> selectByExample(WatchFolderAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    WatchFolderAttr selectByPrimaryKey(String attributeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int updateByExampleSelective(@Param("record") WatchFolderAttr record, @Param("example") WatchFolderAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int updateByExample(@Param("record") WatchFolderAttr record, @Param("example") WatchFolderAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int updateByPrimaryKeySelective(WatchFolderAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderAttrs
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int updateByPrimaryKey(WatchFolderAttr record);
}