package com.smedia.sqzserver.dataservice.dao.base;

import com.smedia.sqzserver.dataservice.model.base.WatchFolderPreset;
import com.smedia.sqzserver.dataservice.model.base.WatchFolderPresetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatchFolderPresetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int countByExample(WatchFolderPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int deleteByExample(WatchFolderPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int deleteByPrimaryKey(String watchFolderPresetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int insert(WatchFolderPreset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int insertSelective(WatchFolderPreset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    List<WatchFolderPreset> selectByExampleWithBLOBs(WatchFolderPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    List<WatchFolderPreset> selectByExample(WatchFolderPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    WatchFolderPreset selectByPrimaryKey(String watchFolderPresetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByExampleSelective(@Param("record") WatchFolderPreset record, @Param("example") WatchFolderPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByExampleWithBLOBs(@Param("record") WatchFolderPreset record, @Param("example") WatchFolderPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByExample(@Param("record") WatchFolderPreset record, @Param("example") WatchFolderPresetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByPrimaryKeySelective(WatchFolderPreset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByPrimaryKeyWithBLOBs(WatchFolderPreset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPresets
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByPrimaryKey(WatchFolderPreset record);
}