package com.smedia.sqzserver.dataservice.dao.base;

import com.smedia.sqzserver.dataservice.model.base.WatchFolderDestination;
import com.smedia.sqzserver.dataservice.model.base.WatchFolderDestinationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatchFolderDestinationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int countByExample(WatchFolderDestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int deleteByExample(WatchFolderDestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int deleteByPrimaryKey(String destinationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int insert(WatchFolderDestination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int insertSelective(WatchFolderDestination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    List<WatchFolderDestination> selectByExample(WatchFolderDestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    WatchFolderDestination selectByPrimaryKey(String destinationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByExampleSelective(@Param("record") WatchFolderDestination record, @Param("example") WatchFolderDestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByExample(@Param("record") WatchFolderDestination record, @Param("example") WatchFolderDestinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByPrimaryKeySelective(WatchFolderDestination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderDestinations
     *
     * @mbggenerated Sat Mar 10 16:01:36 PST 2012
     */
    int updateByPrimaryKey(WatchFolderDestination record);
}