package com.smedia.sqzserver.dataservice.dao.base;

import com.smedia.sqzserver.dataservice.model.base.WatchFolderPlugin;
import com.smedia.sqzserver.dataservice.model.base.WatchFolderPluginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatchFolderPluginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int countByExample(WatchFolderPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int deleteByExample(WatchFolderPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int deleteByPrimaryKey(String pluginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int insert(WatchFolderPlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int insertSelective(WatchFolderPlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    List<WatchFolderPlugin> selectByExample(WatchFolderPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    WatchFolderPlugin selectByPrimaryKey(String pluginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int updateByExampleSelective(@Param("record") WatchFolderPlugin record, @Param("example") WatchFolderPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int updateByExample(@Param("record") WatchFolderPlugin record, @Param("example") WatchFolderPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int updateByPrimaryKeySelective(WatchFolderPlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WatchFolderPlugins
     *
     * @mbggenerated Tue Mar 13 11:34:31 PDT 2012
     */
    int updateByPrimaryKey(WatchFolderPlugin record);
}