package com.smedia.sqzserver.dataservice.dao.base;

import com.smedia.sqzserver.dataservice.model.base.WorkflowCategory;
import com.smedia.sqzserver.dataservice.model.base.WorkflowCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkflowCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    int countByExample(WorkflowCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    int deleteByExample(WorkflowCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    int deleteByPrimaryKey(String workflowCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    int insert(WorkflowCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    int insertSelective(WorkflowCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    List<WorkflowCategory> selectByExample(WorkflowCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    WorkflowCategory selectByPrimaryKey(String workflowCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    int updateByExampleSelective(@Param("record") WorkflowCategory record, @Param("example") WorkflowCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    int updateByExample(@Param("record") WorkflowCategory record, @Param("example") WorkflowCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    int updateByPrimaryKeySelective(WorkflowCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowCategories
     *
     * @mbggenerated Wed Mar 14 19:48:36 MST 2012
     */
    int updateByPrimaryKey(WorkflowCategory record);
}